name: Deploy Contract

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: |
          forge install foundry-rs/forge-std
          forge remappings > remappings.txt

      - name: Build contract
        run: forge build

      - name: Run Simulation
        run: |
          forge script script/Counter.s.sol:CounterScript \
          --fork-url ${{ secrets.RPC_URL }} \
          --private-key ${{ secrets.DEPLOYER_PRIVATE_KEY }}

      - name: Deploy Contract
        run: |
          forge script script/Counter.s.sol:CounterScript \
          --fork-url ${{ secrets.RPC_URL }} \
          --private-key ${{ secrets.DEPLOYER_PRIVATE_KEY }} \
          --broadcast
