name: Deploy Contract

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        run: |
          curl -L https://foundry.paradigm.xyz | bash
          source $HOME/.bashrc
          export PATH="$HOME/.foundry/bin:$PATH"
          foundryup
      
      - name: Check Foundry version
        run: |
          echo "Forge version: $(forge --version)"
          echo "Cast version: $(cast --version)"
          echo "Anvil version: $(anvil --version)"

      - name: Build
        run: forge build

      - name: Run Simulation
        run: |
          forge script script/Counter.s.sol:CounterScript \
          --fork-url ${{ secrets.RPC_URL }} \
          --private-key ${{ secrets.DEPLOYER_PRIVATE_KEY }}

      - name: Deploy Contract
        run: |
          forge script script/Counter.s.sol:CounterScript \
          --fork-url ${{ secrets.RPC_URL }} \
          --private-key ${{ secrets.DEPLOYER_PRIVATE_KEY }} \
          --broadcast
