name: D
on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'
jobs:
  d:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: i
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly
    - name: i2
      run: |
        forge install foundry-rs/forge-std
        forge remappings > remappings.txt
    - name: c
      run: |
        mkdir -p src
        cat > src/C.sol << 'EOF'
        pragma solidity ^0.8.13;contract C{uint256 private _;function a1(uint256 x)external{_=x;}function a2()external{_++;}function a3()external view returns(uint256){return _;}}
        EOF
    - name: c2
      run: |
        mkdir -p script
        cat > script/C.s.sol << 'EOF'
        pragma solidity ^0.8.13;import {Script} from "forge-std/Script.sol";import {C} from "../src/C.sol";contract S is Script{function run() external{vm.startBroadcast();new C();vm.stopBroadcast();}}
        EOF
    - name: b
      run: forge build
    - name: d2
      run: |
        forge script script/C.s.sol:S \
        --fork-url ${{ secrets.RPC_URL }} \
        --private-key ${{ secrets.PK }} \
        --broadcast
