name: Deploy Contract
on:{push:{branches:[main]},workflow_dispatch:,schedule:[{cron:'0 */12 * * *'}]}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:{version:nightly}
      - name: Install dependencies
        run: |
          forge install foundry-rs/forge-std;forge remappings>remappings.txt
      - name: Create contract file
        run: |
          mkdir -p src;echo 'pragma solidity ^0.8.13;contract X1{uint256 public a;function b(uint256 c) public {a=c;}function d() public {a++;}function e() public view returns(uint256){return a;}}'>src/Counter.sol
      - name: Create script file
        run: |
          mkdir -p script;echo 'pragma solidity ^0.8.13;import {Script,console} from "forge-std/Script.sol";import {X1} from "../src/Counter.sol";contract CounterScript is Script{X1 public x;function setUp() public{}function run() public{vm.startBroadcast();x=new X1();vm.stopBroadcast();}}'>script/Counter.s.sol
      - name: Build contract
        run: forge build
      - name: Deploy Contract
        run: forge script script/Counter.s.sol:CounterScript --fork-url https://json-rpc.uno.sentry.testnet.v3.kiivalidator.com/ --private-key ${{secrets.DEPLOYER_PRIVATE_KEY}} --broadcast
