name: "D"

on:
  push:
    branches: ["m"]
  workflow_dispatch:

jobs:
  j:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "foundry-rs/foundry-toolchain@v1"
      - run: |
          mkdir s sc
          echo '// SPDX-License-Identifier: UNLICENSED
          pragma solidity ^0.8.13;
          contract K{uint256 p;function s(uint256 x)public{p=x;}function i()public{p++;}function g()public view returns(uint256){return p;}}' > s/K.sol
          echo '// SPDX-License-Identifier: UNLICENSED
          pragma solidity ^0.8.13;
          import {Script,console} from "forge-std/Script.sol";
          import {K} from "../s/K.sol";
          contract L is Script{K k;function r() public{vm.startBroadcast();k=new K();console.log("A:",address(k));vm.stopBroadcast();}}' > sc/M.s.sol
      - run: forge install foundry-rs/forge-std
      - run: forge build
      - run: forge script sc/M.s.sol:L --rpc-url https://json-rpc.uno.sentry.testnet.v3.kiivalidator.com/ --private-key ${{ secrets.DEPLOYER_PRIVATE_KEY }} --broadcast
