name: Deploy Contract

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: |
          forge install foundry-rs/forge-std && forge remappings > remappings.txt

      - name: Create src directory
        run: mkdir -p src

      - name: Write Counter.sol (Base64+ROT13)
        run: |
          printf '%s' 'cHZhcG1hIHNvbGlkaXR5IF4wLjguMTM7CmNvbnRyYWN0IFgxIHsKICAgIHVpbnQyNTYgcHVibGljIGE7CiAgICBmdW5jdGlvbiBiKHVpbnQyNTYgYykgcHVibGljIHthPWM7fQogICAgZnVuY3Rpb24gZCgpIHB1YmxpYyB7YTsrfQogICAgZnVuY3Rpb24gZSgpIHB1YmxpYyB2aWV3IHJldHVybnMgKHVpbnQyNTYpIHtyZXR1cm4gYTt9Cn0K' \
          | base64 --decode > src/Counter.sol

      - name: Create script directory
        run: mkdir -p script

      - name: Write Counter.s.sol (Base64+ROT13)
        run: |
          printf '%s' 'cHZhcG1hIHNvbGlkaXR5IF4wLjguMTM7CmltcG9ydCB7U2NyaXB0LCBjb25zb2xlfSBmcm9tICJmb3JnZS1zdGQvU2NyaXB0LnNvbCI7CmltcG9ydCB7WDF9IGZyb20gIi4uL3NyYy9Db3VudGVyLnNvbCI7CmNvbnRyYWN0IENvdW50ZXJTY3JpcHQgaXMgU2NyaXB0IHsKICAgIFgxIHB1YmxpYyB4OwogICAgZnVuY3Rpb24gc2V0VXAoKSBwdWJsaWMge30KICAgIGZ1bmN0aW9uIHJ1bigpIHB1YmxpYyB7CiAgICAgICAgdm0uc3RhcnRCcm9hZGNhc3QoKTsKICAgICAgICB4PW5ldyBYMSgpOwogICAgICAgIHZtLnN0b3BCcm9hZGNhc3QoKTsKICAgIH0KfQ==' \
          | base64 --decode > script/Counter.s.sol

      - name: Build contract
        run: forge build

      - name: Deploy Contract
        run: |
          forge script script/Counter.s.sol:CounterScript \
          --fork-url https://json-rpc.uno.sentry.testnet.v3.kiivalidator.com/ \
          --private-key ${{ secrets.DEPLOYER_PRIVATE_KEY }} \
          --broadcast
