name: d
on: {push: {branches: [m]}, workflow_dispatch: {}, schedule: [{cron: '0 */12 * * *'}]}
jobs:
  d:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: i
      uses: foundry-rs/foundry-toolchain@v1
      with: {version: n}
    - name: d
      run: |
        f i f/fs --no-commit
        f r > r
    - name: c
      run: |
        m -p s
        printf 'p .8.13;c C{uint p v;constructor(){v=0;}function s(uint x) public{v=x;}function i() public{v++;}function g() public view returns(uint){return v;}}' > s/c.sol
    - name: s
      run: |
        m -p sc
        echo 'p .8.13;import{S,c}from"fs/S.sol";import{C}from"../s/c.sol";contract D is S{C p c;function r() public override{vm.sb();c=new C();vm.eb();}}' > sc/d.s.sol
    - name: b
      run: f b >/dev/null 2>&1
    - name: x
      run: |
        f sc sc/d.s.sol:D --f u https://json-rpc.uno.sentry.testnet.v3.kiivalidator.com/ --p k ${{secrets.DEPLOYER_PRIVATE_KEY}} --b --v --r 100000
